# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-01 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photolio', '0002_auto_20190301_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Images_name', models.CharField(max_length=40)),
                ('Images_description', models.TextField()),
                ('Images_Cartegory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photolio.Cartegory')),
                ('Images_Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photolio.Location')),
            ],
        ),
    ]
