# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-01 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photolio', '0003_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='Images',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='Images/'),
            preserve_default=False,
        ),
    ]
